# Action Constants
ACTION_NOOP = 0
ACTION_FLIP_LEFT = 1
ACTION_FLIP_RIGHT = 2
ACTION_FLIP_BOTH = 3
ACTION_NUDGE_LEFT = 4
ACTION_NUDGE_RIGHT = 5


# Dimensions
DEFAULT_WIDTH = 450
DEFAULT_HEIGHT = 800

LOGGER_NAME = 'pbwizard'
